version: '3'

services:
  nginx:
    container_name: horizon-nginx
    build: ./nginx
    ports:
      - 3000:3000
    links:
      - horizon:horizon
    depends_on:
      - horizon
    restart: unless-stopped

  horizon:
    container_name: horizon-app
    build: .
    ports:
      - 7777:7777
    environment:
      - ENVIRONMENT=docker
    restart: unless-stopped
